import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import food from '../public/food.png';
import data from '../public/data.png';
import dash from '../public/dash.png';
import { useState } from 'react';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Safwaan Uddin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-[#faebd7] px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-burtons dark:text-neutral-100'>developedby</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-neutral-100' />
              </li>
              <li>
                <a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://github.com/safwaanDK">Resume</a>
              </li>
            </ul>
               
         
          </nav>
          <div className="text-center p-10 ">
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Safwaan Uddin</h2>
          <h3 className='text-2xl py-2 md:text-3xl dark:text-neutral-100'>Web Developer</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-indigo-50'>
          Lorem ipsum dolor sit amet. Ut possimus iste cum explicabo perspiciatis eos doloribus dolorum aut laboriosam voluptate. Qui ratione soluta ab fugit alias eum odit natus non numquam delectus vel laudantium numquam ut voluptatem amet.

          </p>

          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
          <Image src={deved} alt='/' />

          </div>
        
        </section>
        <section>
          <h2 className='text-center p-2 mt-12 font-bold text-3xl text-red-950 dark:text-white'>Portfolio</h2>
          <div className='lg:flex gap-10 '>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 bg-gray-200 dark:bg-slate-400'>
            <Image src={data}  alt='/' />
            <h3 className='text-lg font-medium pt-8 pb-2'>Data Analytics Website</h3>
            <p className='dark:text-white dark:font-bold'>A food menu website is an online platform that provides users with a wide range of food options to choose from. The website usually features menus from various restaurants, cafes, and food trucks in a particular region or locality.</p>

            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 bg-gray-200 dark:bg-slate-400'>
            <Image src={food} alt='/' />
            <h3 className='text-lg font-medium pt-8 pb-2'>Food Menu Website</h3>
            <p className='dark:text-white dark:font-bold'>A data analytics website is a platform that provides users with a suite of tools and resources for analyzing and visualizing data. Typically, such a website will offer various functionalities for data management, including data storage and integration, data cleaning and preprocessing, and data transformation.</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 bg-gray-200 dark:bg-slate-400'>
            <Image src={dash} alt='/' />
            <h3 className='text-lg font-medium pt-8 pb-2'>Dashboard Website</h3>
            <p className='dark:text-white dark:font-bold'>A dashboard website is a user interface that displays important information and data in a visual and easily digestible format. It typically consists of a collection of charts, graphs, and other visual representations of data that provide an overview of key metrics, trends, and performance indicators for a specific project, organization, or system.</p>

            </div>
          </div>
        </section>
        

      </main>
    </div>
  )
}
